CREATE DATABASE IF NOT EXISTS ka_csm_fujian
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE ka_csm_fujian;

CREATE TABLE IF NOT EXISTS managers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE,
  phone VARCHAR(32) NULL,
  region VARCHAR(64) NOT NULL DEFAULT '福建区',
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  display_name VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin', 'supervisor', 'manager') NOT NULL DEFAULT 'manager',
  phone VARCHAR(32) NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  bound_manager_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_bound_manager FOREIGN KEY (bound_manager_id) REFERENCES managers(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL UNIQUE,
  parent_customer_id BIGINT UNSIGNED NULL,
  city VARCHAR(64) NOT NULL,
  industry VARCHAR(80) NOT NULL,
  satisfaction_status ENUM('充分信任', '信任支持', '价值无感', '不够满意', '严重不满') NOT NULL DEFAULT '价值无感',
  risk_level ENUM('低', '中', '高') NOT NULL DEFAULT '中',
  manager_id BIGINT UNSIGNED NOT NULL,
  break_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  renewal_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  repurchase_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  eos_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  remark TEXT NULL,
  last_updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_customers_manager FOREIGN KEY (manager_id) REFERENCES managers(id),
  CONSTRAINT fk_customers_parent FOREIGN KEY (parent_customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  INDEX idx_customers_parent (parent_customer_id),
  INDEX idx_customers_manager (manager_id),
  INDEX idx_customers_status (satisfaction_status),
  INDEX idx_customers_risk (risk_level)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  customer_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(64) NOT NULL,
  department VARCHAR(120) NULL,
  title VARCHAR(120) NULL,
  level ENUM('高层', '中层', '基层') NOT NULL DEFAULT '基层',
  attitude ENUM('充分信任', '信任支持', '价值无感', '不够满意', '严重不满') NOT NULL DEFAULT '信任支持',
  owner_manager_id BIGINT UNSIGNED NOT NULL,
  last_touch_date DATE NULL,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_contacts_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
  CONSTRAINT fk_contacts_owner FOREIGN KEY (owner_manager_id) REFERENCES managers(id),
  INDEX idx_contacts_customer (customer_id),
  INDEX idx_contacts_owner (owner_manager_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS success_plans (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  customer_id BIGINT UNSIGNED NOT NULL,
  scenario_name VARCHAR(180) NOT NULL,
  owner_manager_id BIGINT UNSIGNED NOT NULL,
  stage VARCHAR(120) NOT NULL,
  status ENUM('进行中', '已完成', '暂停') NOT NULL DEFAULT '进行中',
  in_kcp TINYINT(1) NOT NULL DEFAULT 0,
  revenue_progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
  relation_progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
  value_progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
  next_action VARCHAR(255) NULL,
  last_updated_at DATE NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_plans_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
  CONSTRAINT fk_plans_owner FOREIGN KEY (owner_manager_id) REFERENCES managers(id),
  INDEX idx_plans_customer (customer_id),
  INDEX idx_plans_owner (owner_manager_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS success_plan_contacts (
  success_plan_id BIGINT UNSIGNED NOT NULL,
  contact_id BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (success_plan_id, contact_id),
  CONSTRAINT fk_plan_contacts_plan FOREIGN KEY (success_plan_id) REFERENCES success_plans(id) ON DELETE CASCADE,
  CONSTRAINT fk_plan_contacts_contact FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS key_scenarios (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  customer_name VARCHAR(160) NOT NULL,
  scenario_name VARCHAR(255) NOT NULL,
  product_line VARCHAR(120) NULL,
  is_large_volume_scenario VARCHAR(32) NULL,
  owner_name VARCHAR(64) NOT NULL,
  goal_dimension VARCHAR(160) NULL,
  goal_description TEXT NULL,
  business_stage VARCHAR(160) NULL,
  achievement VARCHAR(120) NULL,
  blocking_achieved VARCHAR(80) NULL,
  key_person TEXT NULL,
  key_person_level VARCHAR(160) NULL,
  satisfaction_current VARCHAR(120) NULL,
  quarterly_goal VARCHAR(120) NULL,
  monthly_change VARCHAR(160) NULL,
  project_stage VARCHAR(120) NULL,
  business_need_insight VARCHAR(80) NULL,
  business_value_goal VARCHAR(120) NULL,
  sla_goal VARCHAR(120) NULL,
  poc_effect VARCHAR(180) NULL,
  business_value_realization VARCHAR(160) NULL,
  key_person_recognition VARCHAR(120) NULL,
  sla_achievement VARCHAR(120) NULL,
  satisfaction_risk VARCHAR(120) NULL,
  delivery_mot_effect VARCHAR(180) NULL,
  after_sales_mot_effect VARCHAR(180) NULL,
  other_key_activity_effect VARCHAR(180) NULL,
  key_gap TEXT NULL,
  june_key_action TEXT NULL,
  next_check_date VARCHAR(64) NULL,
  last_updated_at DATE NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_key_scenarios_owner (owner_name),
  INDEX idx_key_scenarios_customer (customer_name),
  INDEX idx_key_scenarios_stage (business_stage)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS service_renewals (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  customer_name VARCHAR(160) NOT NULL,
  owner_name VARCHAR(64) NOT NULL,
  management_sheet VARCHAR(180) NULL,
  renewal_target DECIMAL(12,2) NOT NULL DEFAULT 0,
  non_eos_expired_devices DECIMAL(12,2) NOT NULL DEFAULT 0,
  renewed_devices DECIMAL(12,2) NOT NULL DEFAULT 0,
  renewed_order_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  device_renewal_rate DECIMAL(12,4) NOT NULL DEFAULT 0,
  remaining_renewal_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  eos_replacement_target DECIMAL(12,2) NOT NULL DEFAULT 0,
  eos_expired_devices DECIMAL(12,2) NOT NULL DEFAULT 0,
  replaced_devices DECIMAL(12,2) NOT NULL DEFAULT 0,
  replacement_order_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  eos_replacement_rate DECIMAL(12,4) NOT NULL DEFAULT 0,
  remaining_replacement_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  last_updated_at DATE NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_service_renewals_owner (owner_name),
  INDEX idx_service_renewals_customer (customer_name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS end_to_end_projects (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  region VARCHAR(64) NULL,
  group_customer VARCHAR(160) NOT NULL,
  secondary_unit VARCHAR(160) NULL,
  owner_name VARCHAR(64) NOT NULL,
  project_name VARCHAR(255) NOT NULL,
  solution VARCHAR(160) NULL,
  product VARCHAR(160) NULL,
  project_level VARCHAR(120) NULL,
  is_blocking_project VARCHAR(32) NULL,
  project_background TEXT NULL,
  production_stage VARCHAR(180) NULL,
  project_progress VARCHAR(180) NULL,
  satisfaction_risk VARCHAR(160) NULL,
  business_value TEXT NULL,
  latest_recognition VARCHAR(120) NULL,
  current_month_recognition VARCHAR(120) NULL,
  previous_month_recognition VARCHAR(120) NULL,
  sla_achieved VARCHAR(120) NULL,
  redundancy_effective VARCHAR(160) NULL,
  known_risk_cleared VARCHAR(180) NULL,
  risk_perception VARCHAR(180) NULL,
  key_remark TEXT NULL,
  next_focus TEXT NULL,
  next_follow_date VARCHAR(64) NULL,
  project_control VARCHAR(180) NULL,
  project_control_remark TEXT NULL,
  atx_original_need_clear VARCHAR(180) NULL,
  atx_standard_product_fit VARCHAR(180) NULL,
  atx_customization_risk VARCHAR(180) NULL,
  atx_service_cost_covered VARCHAR(120) NULL,
  atx_review_material TEXT NULL,
  poc_effect VARCHAR(180) NULL,
  poc_remark TEXT NULL,
  poc_key_person_need_clear VARCHAR(180) NULL,
  poc_plan_advantage VARCHAR(180) NULL,
  poc_test_condition_ready VARCHAR(180) NULL,
  poc_review_material TEXT NULL,
  startup_meeting VARCHAR(180) NULL,
  startup_remark TEXT NULL,
  delivery_job_need_clear VARCHAR(180) NULL,
  requirement_material TEXT NULL,
  hld_design_effect VARCHAR(180) NULL,
  hld_material TEXT NULL,
  external_kickoff VARCHAR(180) NULL,
  external_kickoff_material TEXT NULL,
  project_risk_progress_visible VARCHAR(180) NULL,
  project_management_material TEXT NULL,
  prr_effect VARCHAR(180) NULL,
  prr_material TEXT NULL,
  stage_value_perception VARCHAR(180) NULL,
  stage_value_material TEXT NULL,
  value_realization VARCHAR(180) NULL,
  value_material TEXT NULL,
  ops_handover VARCHAR(180) NULL,
  ops_handover_material TEXT NULL,
  executive_review VARCHAR(180) NULL,
  executive_review_material TEXT NULL,
  continued_expansion VARCHAR(180) NULL,
  continued_expansion_remark TEXT NULL,
  last_updated_at DATE NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_e2e_projects_owner (owner_name),
  INDEX idx_e2e_projects_customer (group_customer),
  INDEX idx_e2e_projects_progress (project_progress)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS weekly_tasks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  customer_id BIGINT UNSIGNED NOT NULL,
  success_plan_id BIGINT UNSIGNED NULL,
  title VARCHAR(255) NOT NULL,
  owner_manager_id BIGINT UNSIGNED NOT NULL,
  source VARCHAR(80) NOT NULL DEFAULT '主管安排',
  plan_date DATE NOT NULL,
  status ENUM('未开始', '进行中', '逾期', '已完成') NOT NULL DEFAULT '未开始',
  result_note TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_tasks_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
  CONSTRAINT fk_tasks_plan FOREIGN KEY (success_plan_id) REFERENCES success_plans(id) ON DELETE SET NULL,
  CONSTRAINT fk_tasks_owner FOREIGN KEY (owner_manager_id) REFERENCES managers(id),
  INDEX idx_tasks_owner_date (owner_manager_id, plan_date),
  INDEX idx_tasks_status (status)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS push_config (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  webhook_url VARCHAR(500) NULL,
  push_time VARCHAR(16) NOT NULL DEFAULT '18:00',
  timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
  enabled TINYINT(1) NOT NULL DEFAULT 0,
  include_customer TINYINT(1) NOT NULL DEFAULT 1,
  include_scenario TINYINT(1) NOT NULL DEFAULT 1,
  include_status TINYINT(1) NOT NULL DEFAULT 1,
  include_plan_date TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS push_recipients (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  config_id BIGINT UNSIGNED NOT NULL,
  manager_id BIGINT UNSIGNED NOT NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  CONSTRAINT fk_push_recipients_config FOREIGN KEY (config_id) REFERENCES push_config(id) ON DELETE CASCADE,
  CONSTRAINT fk_push_recipients_manager FOREIGN KEY (manager_id) REFERENCES managers(id) ON DELETE CASCADE,
  UNIQUE KEY uniq_push_recipient (config_id, manager_id)
) ENGINE=InnoDB;
